categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'performace'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Build and CI'
    labels:
      - 'build'
      - 'ci'
  - title: 'Documentation'
    labels:
      - 'docs'
  - title: 'Improvements'
    labels:
      - 'test'
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
