name: 'Set variables'
description: 'Set variables. Uses github context'
outputs:
  is_release:
    description: "Is release?"
    value: ${{ steps.set_variables.outputs.is_release }}
  release_version:
    description: "Release version"
    value: ${{ steps.set_variables.outputs.release_version }}
  git_ref:
    description: "Git ref"
    value: ${{ steps.set_variables.outputs.ref }}
  radixdlt_image:
    description: "radixdlt image"
    value: ${{ steps.set_variables.outputs.radixdlt_image }}
  keygen_image:
    description: "keygen image"
    value: ${{ steps.set_variables.outputs.keygen_image }}
runs:
  using: "composite"
  steps:
    - id: set_variables
      run: |
        echo "GITHUB_REF $GITHUB_REF"
        GH_EVENT_NAME="${{ github.event_name }}"
        if [[ ! -z $GH_EVENT_NAME ]] && [[ "$GH_EVENT_NAME" == "release" ]] ;then
          echo "Workflow triggered by a release event"
          echo "Release version ${{ github.event.release.tag_name }}"
          echo "is_release=true" >> $GITHUB_OUTPUT
          echo "release_version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "ref=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "radixdlt_image=radixdlt/radixdlt-core" >> $GITHUB_OUTPUT
          echo "keygen_image=radixdlt/keygen" >> $GITHUB_OUTPUT

          echo "is_release: true"
          echo "release_version: ${{ github.event.release.tag_name }}"
          echo "ref: ${{ github.event.release.tag_name }}"
          echo "radixdlt_image: radixdlt/radixdlt"
          echo "keygen_image: radixdlt/keygen"
        else
          if [[ ! -z $GH_EVENT_NAME ]] && [[ "$GH_EVENT_NAME" == "pull_request" ]] ;then
            echo "Workflow triggered by push to a PR"
            echo "ref=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "Workflow triggered by push to a branch"
            echo "ref=$(echo $GITHUB_REF)" >> $GITHUB_OUTPUT
          fi
          echo "is_release=false" >> $GITHUB_OUTPUT
          echo "radixdlt_image=eu.gcr.io/dev-container-repo/radixdlt-core" >> $GITHUB_OUTPUT
          echo "keygen_image=eu.gcr.io/dev-container-repo/keygen" >> $GITHUB_OUTPUT

          echo "is_release: false"
          echo "ref: $GITHUB_REF"
          echo "radixdlt_image: eu.gcr.io/dev-container-repo/radixdlt-core"
          echo "keygen_image: eu.gcr.io/dev-container-repo/keygen"
        fi
      shell: bash
