/*
 * Radix System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radixdlt.api.system.openapitools.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Address
 */
@JsonPropertyOrder({
  Address.JSON_PROPERTY_URI,
  Address.JSON_PROPERTY_BLACKLISTED,
  Address.JSON_PROPERTY_LAST_CONNECTION_STATUS
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-20T22:11:26.095756951+01:00[Europe/Warsaw]")
public class Address {
  public static final String JSON_PROPERTY_URI = "uri";
  private String uri;

  public static final String JSON_PROPERTY_BLACKLISTED = "blacklisted";
  private Boolean blacklisted;

  /**
   * Gets or Sets lastConnectionStatus
   */
  public enum LastConnectionStatusEnum {
    SUCCESS("SUCCESS"),
    
    FAILURE("FAILURE"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    LastConnectionStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LastConnectionStatusEnum fromValue(String value) {
      for (LastConnectionStatusEnum b : LastConnectionStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LAST_CONNECTION_STATUS = "last_connection_status";
  private LastConnectionStatusEnum lastConnectionStatus;

  public Address uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUri() {
    return uri;
  }


  @JsonProperty(JSON_PROPERTY_URI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUri(String uri) {
    this.uri = uri;
  }


  public Address blacklisted(Boolean blacklisted) {
    this.blacklisted = blacklisted;
    return this;
  }

   /**
   * Get blacklisted
   * @return blacklisted
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BLACKLISTED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getBlacklisted() {
    return blacklisted;
  }


  @JsonProperty(JSON_PROPERTY_BLACKLISTED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBlacklisted(Boolean blacklisted) {
    this.blacklisted = blacklisted;
  }


  public Address lastConnectionStatus(LastConnectionStatusEnum lastConnectionStatus) {
    this.lastConnectionStatus = lastConnectionStatus;
    return this;
  }

   /**
   * Get lastConnectionStatus
   * @return lastConnectionStatus
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LAST_CONNECTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LastConnectionStatusEnum getLastConnectionStatus() {
    return lastConnectionStatus;
  }


  @JsonProperty(JSON_PROPERTY_LAST_CONNECTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastConnectionStatus(LastConnectionStatusEnum lastConnectionStatus) {
    this.lastConnectionStatus = lastConnectionStatus;
  }


  /**
   * Return true if this Address object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.uri, address.uri) &&
        Objects.equals(this.blacklisted, address.blacklisted) &&
        Objects.equals(this.lastConnectionStatus, address.lastConnectionStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, blacklisted, lastConnectionStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    blacklisted: ").append(toIndentedString(blacklisted)).append("\n");
    sb.append("    lastConnectionStatus: ").append(toIndentedString(lastConnectionStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

