/*
 * Radix System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radixdlt.api.system.openapitools.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * HealthResponseUnknownReportedForksHashes
 */
@JsonPropertyOrder({
  HealthResponseUnknownReportedForksHashes.JSON_PROPERTY_FORK_HASH,
  HealthResponseUnknownReportedForksHashes.JSON_PROPERTY_REPORTED_BY
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-20T22:11:26.095756951+01:00[Europe/Warsaw]")
public class HealthResponseUnknownReportedForksHashes {
  public static final String JSON_PROPERTY_FORK_HASH = "fork_hash";
  private String forkHash;

  public static final String JSON_PROPERTY_REPORTED_BY = "reported_by";
  private List<String> reportedBy = new ArrayList<>();

  public HealthResponseUnknownReportedForksHashes forkHash(String forkHash) {
    this.forkHash = forkHash;
    return this;
  }

   /**
   * Get forkHash
   * @return forkHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FORK_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getForkHash() {
    return forkHash;
  }


  @JsonProperty(JSON_PROPERTY_FORK_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setForkHash(String forkHash) {
    this.forkHash = forkHash;
  }


  public HealthResponseUnknownReportedForksHashes reportedBy(List<String> reportedBy) {
    this.reportedBy = reportedBy;
    return this;
  }

  public HealthResponseUnknownReportedForksHashes addReportedByItem(String reportedByItem) {
    this.reportedBy.add(reportedByItem);
    return this;
  }

   /**
   * Get reportedBy
   * @return reportedBy
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_REPORTED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getReportedBy() {
    return reportedBy;
  }


  @JsonProperty(JSON_PROPERTY_REPORTED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReportedBy(List<String> reportedBy) {
    this.reportedBy = reportedBy;
  }


  /**
   * Return true if this HealthResponse_unknown_reported_forks_hashes object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HealthResponseUnknownReportedForksHashes healthResponseUnknownReportedForksHashes = (HealthResponseUnknownReportedForksHashes) o;
    return Objects.equals(this.forkHash, healthResponseUnknownReportedForksHashes.forkHash) &&
        Objects.equals(this.reportedBy, healthResponseUnknownReportedForksHashes.reportedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(forkHash, reportedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HealthResponseUnknownReportedForksHashes {\n");
    sb.append("    forkHash: ").append(toIndentedString(forkHash)).append("\n");
    sb.append("    reportedBy: ").append(toIndentedString(reportedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

