version: '2.1'
services:
  core0:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core0
      RADIXDLT_NETWORK_SEEDS_REMOTE: core1,core2
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_0_PRIVKEY}
    networks:
      - three_node_universe
  core1:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core1
      RADIXDLT_NETWORK_SEEDS_REMOTE: core0,core2
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_1_PRIVKEY}
    networks:
      - three_node_universe
  core2:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core2
      RADIXDLT_NETWORK_SEEDS_REMOTE: core0,core1
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_2_PRIVKEY}
    networks:
      - three_node_universe
    networks:
      - three_node_universe
networks:
  three_node_universe:
    external:
      name: radix_default
