version: '2.1'
services:
  core0:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core0
      RADIXDLT_NETWORK_SEEDS_REMOTE: "radix://${RADIXDLT_VALIDATOR_1_PUBKEY}@core1,radix://${RADIXDLT_VALIDATOR_2_PUBKEY}@core2,radix://${RADIXDLT_VALIDATOR_3_PUBKEY}@core3"
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_0_PRIVKEY}
    networks:
      - four_nodes
    ports:
      - "3333:3333"
      - "8080:8080"
      - "9011:9011"
      - "50505:50505"
      - "10000:10000/tcp"
      - "20000:20000/tcp"
      - "30000:30000/tcp"
  core1:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core1
      RADIXDLT_NETWORK_SEEDS_REMOTE: "radix://${RADIXDLT_VALIDATOR_0_PUBKEY}@core0,radix://${RADIXDLT_VALIDATOR_2_PUBKEY}@core2,radix://${RADIXDLT_VALIDATOR_3_PUBKEY}@core3"
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_1_PRIVKEY}
    networks:
      - four_nodes
    ports:
      - "3334:3333"
      - "8081:8080"
      - "9012:9011"
      - "50506:50505"
  core2:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core2
      RADIXDLT_NETWORK_SEEDS_REMOTE: "radix://${RADIXDLT_VALIDATOR_0_PUBKEY}@core0,radix://${RADIXDLT_VALIDATOR_1_PUBKEY}@core1,radix://${RADIXDLT_VALIDATOR_3_PUBKEY}@core3"
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_2_PRIVKEY}
    networks:
      - four_nodes
    ports:
      - "3335:3333"
      - "8082:8080"
      - "9013:9011"
      - "50507:50505"
  core3:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core3
      RADIXDLT_NETWORK_SEEDS_REMOTE: "radix://${RADIXDLT_VALIDATOR_0_PUBKEY}@core0,radix://${RADIXDLT_VALIDATOR_1_PUBKEY}@core1,radix://${RADIXDLT_VALIDATOR_2_PUBKEY}@core2"
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_3_PRIVKEY}
    networks:
      - four_nodes
    ports:
      - "3336:3333"
      - "8083:8080"
      - "9014:9011"
      - "50508:50505"
networks:
  four_nodes:
