/*
 * Wallet/Explorer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Action;

/**
 * ConstructionBuildRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-25T08:11:19.875906-07:00[America/Los_Angeles]")
public class ConstructionBuildRequest {
  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private List<Action> actions = new ArrayList<Action>();

  public static final String SERIALIZED_NAME_FEE_PAYER = "feePayer";
  @SerializedName(SERIALIZED_NAME_FEE_PAYER)
  private String feePayer;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_DISABLE_RESOURCE_ALLOCATION_AND_DESTROY = "disableResourceAllocationAndDestroy";
  @SerializedName(SERIALIZED_NAME_DISABLE_RESOURCE_ALLOCATION_AND_DESTROY)
  private Boolean disableResourceAllocationAndDestroy;


  public ConstructionBuildRequest actions(List<Action> actions) {
    
    this.actions = actions;
    return this;
  }

  public ConstructionBuildRequest addActionsItem(Action actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Action> getActions() {
    return actions;
  }


  public void setActions(List<Action> actions) {
    this.actions = actions;
  }


  public ConstructionBuildRequest feePayer(String feePayer) {
    
    this.feePayer = feePayer;
    return this;
  }

   /**
   * Get feePayer
   * @return feePayer
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFeePayer() {
    return feePayer;
  }


  public void setFeePayer(String feePayer) {
    this.feePayer = feePayer;
  }


  public ConstructionBuildRequest message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ConstructionBuildRequest disableResourceAllocationAndDestroy(Boolean disableResourceAllocationAndDestroy) {
    
    this.disableResourceAllocationAndDestroy = disableResourceAllocationAndDestroy;
    return this;
  }

   /**
   * Get disableResourceAllocationAndDestroy
   * @return disableResourceAllocationAndDestroy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDisableResourceAllocationAndDestroy() {
    return disableResourceAllocationAndDestroy;
  }


  public void setDisableResourceAllocationAndDestroy(Boolean disableResourceAllocationAndDestroy) {
    this.disableResourceAllocationAndDestroy = disableResourceAllocationAndDestroy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConstructionBuildRequest constructionBuildRequest = (ConstructionBuildRequest) o;
    return Objects.equals(this.actions, constructionBuildRequest.actions) &&
        Objects.equals(this.feePayer, constructionBuildRequest.feePayer) &&
        Objects.equals(this.message, constructionBuildRequest.message) &&
        Objects.equals(this.disableResourceAllocationAndDestroy, constructionBuildRequest.disableResourceAllocationAndDestroy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actions, feePayer, message, disableResourceAllocationAndDestroy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConstructionBuildRequest {\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    feePayer: ").append(toIndentedString(feePayer)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    disableResourceAllocationAndDestroy: ").append(toIndentedString(disableResourceAllocationAndDestroy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

