/*
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radixdlt.api.gateway.openapitools.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * AccountStakeEntry
 */
@JsonPropertyOrder({
  AccountStakeEntry.JSON_PROPERTY_VALIDATOR_IDENTIFIER,
  AccountStakeEntry.JSON_PROPERTY_DELEGATED_STAKE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-27T00:28:54.766735-06:00[America/Chicago]")
public class AccountStakeEntry {
  public static final String JSON_PROPERTY_VALIDATOR_IDENTIFIER = "validator_identifier";
  private ValidatorIdentifier validatorIdentifier;

  public static final String JSON_PROPERTY_DELEGATED_STAKE = "delegated_stake";
  private TokenAmount delegatedStake;


  public AccountStakeEntry validatorIdentifier(ValidatorIdentifier validatorIdentifier) {
    this.validatorIdentifier = validatorIdentifier;
    return this;
  }

   /**
   * Get validatorIdentifier
   * @return validatorIdentifier
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VALIDATOR_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ValidatorIdentifier getValidatorIdentifier() {
    return validatorIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATOR_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValidatorIdentifier(ValidatorIdentifier validatorIdentifier) {
    this.validatorIdentifier = validatorIdentifier;
  }


  public AccountStakeEntry delegatedStake(TokenAmount delegatedStake) {
    this.delegatedStake = delegatedStake;
    return this;
  }

   /**
   * Get delegatedStake
   * @return delegatedStake
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DELEGATED_STAKE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TokenAmount getDelegatedStake() {
    return delegatedStake;
  }


  @JsonProperty(JSON_PROPERTY_DELEGATED_STAKE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDelegatedStake(TokenAmount delegatedStake) {
    this.delegatedStake = delegatedStake;
  }


  /**
   * Return true if this AccountStakeEntry object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountStakeEntry accountStakeEntry = (AccountStakeEntry) o;
    return Objects.equals(this.validatorIdentifier, accountStakeEntry.validatorIdentifier) &&
        Objects.equals(this.delegatedStake, accountStakeEntry.delegatedStake);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validatorIdentifier, delegatedStake);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountStakeEntry {\n");
    sb.append("    validatorIdentifier: ").append(toIndentedString(validatorIdentifier)).append("\n");
    sb.append("    delegatedStake: ").append(toIndentedString(delegatedStake)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

