/*
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radixdlt.api.gateway.openapitools.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * AccountUnstakesResponse
 */
@JsonPropertyOrder({
  AccountUnstakesResponse.JSON_PROPERTY_LEDGER_STATE,
  AccountUnstakesResponse.JSON_PROPERTY_UNSTAKES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-02T13:11:38.357742-06:00[America/Chicago]")
public class AccountUnstakesResponse {
  public static final String JSON_PROPERTY_LEDGER_STATE = "ledger_state";
  private LedgerState ledgerState;

  public static final String JSON_PROPERTY_UNSTAKES = "unstakes";
  private List<AccountUnstakeEntry> unstakes = new ArrayList<>();


  public AccountUnstakesResponse ledgerState(LedgerState ledgerState) {
    this.ledgerState = ledgerState;
    return this;
  }

   /**
   * Get ledgerState
   * @return ledgerState
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LEDGER_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LedgerState getLedgerState() {
    return ledgerState;
  }


  @JsonProperty(JSON_PROPERTY_LEDGER_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLedgerState(LedgerState ledgerState) {
    this.ledgerState = ledgerState;
  }


  public AccountUnstakesResponse unstakes(List<AccountUnstakeEntry> unstakes) {
    this.unstakes = unstakes;
    return this;
  }

  public AccountUnstakesResponse addUnstakesItem(AccountUnstakeEntry unstakesItem) {
    this.unstakes.add(unstakesItem);
    return this;
  }

   /**
   * Get unstakes
   * @return unstakes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UNSTAKES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AccountUnstakeEntry> getUnstakes() {
    return unstakes;
  }


  @JsonProperty(JSON_PROPERTY_UNSTAKES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnstakes(List<AccountUnstakeEntry> unstakes) {
    this.unstakes = unstakes;
  }


  /**
   * Return true if this AccountUnstakesResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountUnstakesResponse accountUnstakesResponse = (AccountUnstakesResponse) o;
    return Objects.equals(this.ledgerState, accountUnstakesResponse.ledgerState) &&
        Objects.equals(this.unstakes, accountUnstakesResponse.unstakes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ledgerState, unstakes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountUnstakesResponse {\n");
    sb.append("    ledgerState: ").append(toIndentedString(ledgerState)).append("\n");
    sb.append("    unstakes: ").append(toIndentedString(unstakes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

