/*
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radixdlt.api.gateway.openapitools.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.radixdlt.api.gateway.openapitools.JSON;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * TransactionBuildResponseSuccess
 */
@JsonPropertyOrder({
  TransactionBuildResponseSuccess.JSON_PROPERTY_TRANSACTION_BUILD
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-27T11:34:49.994520-06:00[America/Chicago]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = TransactionBuildResponseError.class, name = "TransactionBuildResponseError"),
  @JsonSubTypes.Type(value = TransactionBuildResponseSuccess.class, name = "TransactionBuildResponseSuccess"),
})

public class TransactionBuildResponseSuccess extends TransactionBuildResponse {
  public static final String JSON_PROPERTY_TRANSACTION_BUILD = "transaction_build";
  private TransactionBuild transactionBuild;


  public TransactionBuildResponseSuccess transactionBuild(TransactionBuild transactionBuild) {
    this.transactionBuild = transactionBuild;
    return this;
  }

   /**
   * Get transactionBuild
   * @return transactionBuild
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_BUILD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransactionBuild getTransactionBuild() {
    return transactionBuild;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_BUILD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionBuild(TransactionBuild transactionBuild) {
    this.transactionBuild = transactionBuild;
  }


  /**
   * Return true if this TransactionBuildResponseSuccess object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionBuildResponseSuccess transactionBuildResponseSuccess = (TransactionBuildResponseSuccess) o;
    return Objects.equals(this.transactionBuild, transactionBuildResponseSuccess.transactionBuild) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionBuild, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionBuildResponseSuccess {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    transactionBuild: ").append(toIndentedString(transactionBuild)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("TransactionBuildResponseError", TransactionBuildResponseError.class);
  mappings.put("TransactionBuildResponseSuccess", TransactionBuildResponseSuccess.class);
  mappings.put("TransactionBuildResponseSuccess", TransactionBuildResponseSuccess.class);
  JSON.registerDiscriminator(TransactionBuildResponseSuccess.class, "type", mappings);
}
}

