/*
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radixdlt.api.gateway.openapitools.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * TransactionRulesResponse
 */
@JsonPropertyOrder({
  TransactionRulesResponse.JSON_PROPERTY_LEDGER_STATE,
  TransactionRulesResponse.JSON_PROPERTY_TRANSACTION_RULES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-27T11:34:49.994520-06:00[America/Chicago]")
public class TransactionRulesResponse {
  public static final String JSON_PROPERTY_LEDGER_STATE = "ledger_state";
  private LedgerState ledgerState;

  public static final String JSON_PROPERTY_TRANSACTION_RULES = "transaction_rules";
  private TransactionRules transactionRules;


  public TransactionRulesResponse ledgerState(LedgerState ledgerState) {
    this.ledgerState = ledgerState;
    return this;
  }

   /**
   * Get ledgerState
   * @return ledgerState
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LEDGER_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LedgerState getLedgerState() {
    return ledgerState;
  }


  @JsonProperty(JSON_PROPERTY_LEDGER_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLedgerState(LedgerState ledgerState) {
    this.ledgerState = ledgerState;
  }


  public TransactionRulesResponse transactionRules(TransactionRules transactionRules) {
    this.transactionRules = transactionRules;
    return this;
  }

   /**
   * Get transactionRules
   * @return transactionRules
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRANSACTION_RULES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransactionRules getTransactionRules() {
    return transactionRules;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_RULES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionRules(TransactionRules transactionRules) {
    this.transactionRules = transactionRules;
  }


  /**
   * Return true if this TransactionRulesResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionRulesResponse transactionRulesResponse = (TransactionRulesResponse) o;
    return Objects.equals(this.ledgerState, transactionRulesResponse.ledgerState) &&
        Objects.equals(this.transactionRules, transactionRulesResponse.transactionRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ledgerState, transactionRules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionRulesResponse {\n");
    sb.append("    ledgerState: ").append(toIndentedString(ledgerState)).append("\n");
    sb.append("    transactionRules: ").append(toIndentedString(transactionRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

