/*
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radixdlt.api.gateway.openapitools.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * TransactionFinalizeRequest
 */
@JsonPropertyOrder({
  TransactionFinalizeRequest.JSON_PROPERTY_NETWORK,
  TransactionFinalizeRequest.JSON_PROPERTY_UNSIGNED_TRANSACTION,
  TransactionFinalizeRequest.JSON_PROPERTY_SIGNATURE,
  TransactionFinalizeRequest.JSON_PROPERTY_SUBMIT
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T13:12:37.554814-06:00[America/Chicago]")
public class TransactionFinalizeRequest {
  public static final String JSON_PROPERTY_NETWORK = "network";
  private String network;

  public static final String JSON_PROPERTY_UNSIGNED_TRANSACTION = "unsigned_transaction";
  private String unsignedTransaction;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  private TransactionFinalizeRequestSignature signature;

  public static final String JSON_PROPERTY_SUBMIT = "submit";
  private Boolean submit;


  public TransactionFinalizeRequest network(String network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetwork(String network) {
    this.network = network;
  }


  public TransactionFinalizeRequest unsignedTransaction(String unsignedTransaction) {
    this.unsignedTransaction = unsignedTransaction;
    return this;
  }

   /**
   * Get unsignedTransaction
   * @return unsignedTransaction
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UNSIGNED_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUnsignedTransaction() {
    return unsignedTransaction;
  }


  @JsonProperty(JSON_PROPERTY_UNSIGNED_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnsignedTransaction(String unsignedTransaction) {
    this.unsignedTransaction = unsignedTransaction;
  }


  public TransactionFinalizeRequest signature(TransactionFinalizeRequestSignature signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransactionFinalizeRequestSignature getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignature(TransactionFinalizeRequestSignature signature) {
    this.signature = signature;
  }


  public TransactionFinalizeRequest submit(Boolean submit) {
    this.submit = submit;
    return this;
  }

   /**
   * Get submit
   * @return submit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSubmit() {
    return submit;
  }


  @JsonProperty(JSON_PROPERTY_SUBMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubmit(Boolean submit) {
    this.submit = submit;
  }


  /**
   * Return true if this TransactionFinalizeRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionFinalizeRequest transactionFinalizeRequest = (TransactionFinalizeRequest) o;
    return Objects.equals(this.network, transactionFinalizeRequest.network) &&
        Objects.equals(this.unsignedTransaction, transactionFinalizeRequest.unsignedTransaction) &&
        Objects.equals(this.signature, transactionFinalizeRequest.signature) &&
        Objects.equals(this.submit, transactionFinalizeRequest.submit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(network, unsignedTransaction, signature, submit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionFinalizeRequest {\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    unsignedTransaction: ").append(toIndentedString(unsignedTransaction)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    submit: ").append(toIndentedString(submit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

