/*
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radixdlt.api.gateway.openapitools.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.radixdlt.api.gateway.openapitools.JSON;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * UnstakeTokens
 */
@JsonPropertyOrder({
  UnstakeTokens.JSON_PROPERTY_FROM_VALIDATOR,
  UnstakeTokens.JSON_PROPERTY_TO_ACCOUNT,
  UnstakeTokens.JSON_PROPERTY_AMOUNT
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-30T23:39:48.223160-06:00[America/Chicago]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = BurnTokens.class, name = "BurnTokens"),
  @JsonSubTypes.Type(value = MintTokens.class, name = "MintTokens"),
  @JsonSubTypes.Type(value = StakeTokens.class, name = "StakeTokens"),
  @JsonSubTypes.Type(value = TransferTokens.class, name = "TransferTokens"),
  @JsonSubTypes.Type(value = UnstakeTokens.class, name = "UnstakeTokens"),
})

public class UnstakeTokens extends Action {
  public static final String JSON_PROPERTY_FROM_VALIDATOR = "from_validator";
  private ValidatorIdentifier fromValidator;

  public static final String JSON_PROPERTY_TO_ACCOUNT = "to_account";
  private AccountIdentifier toAccount;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private TokenAmount amount;


  public UnstakeTokens fromValidator(ValidatorIdentifier fromValidator) {
    this.fromValidator = fromValidator;
    return this;
  }

   /**
   * Get fromValidator
   * @return fromValidator
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FROM_VALIDATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ValidatorIdentifier getFromValidator() {
    return fromValidator;
  }


  @JsonProperty(JSON_PROPERTY_FROM_VALIDATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromValidator(ValidatorIdentifier fromValidator) {
    this.fromValidator = fromValidator;
  }


  public UnstakeTokens toAccount(AccountIdentifier toAccount) {
    this.toAccount = toAccount;
    return this;
  }

   /**
   * Get toAccount
   * @return toAccount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AccountIdentifier getToAccount() {
    return toAccount;
  }


  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToAccount(AccountIdentifier toAccount) {
    this.toAccount = toAccount;
  }


  public UnstakeTokens amount(TokenAmount amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TokenAmount getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(TokenAmount amount) {
    this.amount = amount;
  }


  /**
   * Return true if this UnstakeTokens object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnstakeTokens unstakeTokens = (UnstakeTokens) o;
    return Objects.equals(this.fromValidator, unstakeTokens.fromValidator) &&
        Objects.equals(this.toAccount, unstakeTokens.toAccount) &&
        Objects.equals(this.amount, unstakeTokens.amount) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromValidator, toAccount, amount, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnstakeTokens {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    fromValidator: ").append(toIndentedString(fromValidator)).append("\n");
    sb.append("    toAccount: ").append(toIndentedString(toAccount)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("BurnTokens", BurnTokens.class);
  mappings.put("MintTokens", MintTokens.class);
  mappings.put("StakeTokens", StakeTokens.class);
  mappings.put("TransferTokens", TransferTokens.class);
  mappings.put("UnstakeTokens", UnstakeTokens.class);
  mappings.put("UnstakeTokens", UnstakeTokens.class);
  JSON.registerDiscriminator(UnstakeTokens.class, "type", mappings);
}
}

