/*
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radixdlt.api.gateway.openapitools.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * ValidatorInfo
 */
@JsonPropertyOrder({
  ValidatorInfo.JSON_PROPERTY_OWNER_STAKE,
  ValidatorInfo.JSON_PROPERTY_UPTIME
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-27T01:49:33.060927-06:00[America/Chicago]")
public class ValidatorInfo {
  public static final String JSON_PROPERTY_OWNER_STAKE = "owner_stake";
  private TokenAmount ownerStake;

  public static final String JSON_PROPERTY_UPTIME = "uptime";
  private ValidatorUptime uptime;


  public ValidatorInfo ownerStake(TokenAmount ownerStake) {
    this.ownerStake = ownerStake;
    return this;
  }

   /**
   * Get ownerStake
   * @return ownerStake
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_OWNER_STAKE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TokenAmount getOwnerStake() {
    return ownerStake;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_STAKE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOwnerStake(TokenAmount ownerStake) {
    this.ownerStake = ownerStake;
  }


  public ValidatorInfo uptime(ValidatorUptime uptime) {
    this.uptime = uptime;
    return this;
  }

   /**
   * Get uptime
   * @return uptime
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UPTIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ValidatorUptime getUptime() {
    return uptime;
  }


  @JsonProperty(JSON_PROPERTY_UPTIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUptime(ValidatorUptime uptime) {
    this.uptime = uptime;
  }


  /**
   * Return true if this ValidatorInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidatorInfo validatorInfo = (ValidatorInfo) o;
    return Objects.equals(this.ownerStake, validatorInfo.ownerStake) &&
        Objects.equals(this.uptime, validatorInfo.uptime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ownerStake, uptime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidatorInfo {\n");
    sb.append("    ownerStake: ").append(toIndentedString(ownerStake)).append("\n");
    sb.append("    uptime: ").append(toIndentedString(uptime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

