/*
 * Wallet/Explorer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AccountStakesResponseStakes;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountStakesResponse
 */
public class AccountStakesResponseTest {
    private final AccountStakesResponse model = new AccountStakesResponse();

    /**
     * Model tests for AccountStakesResponse
     */
    @Test
    public void testAccountStakesResponse() {
        // TODO: test AccountStakesResponse
    }

    /**
     * Test the property 'stakes'
     */
    @Test
    public void stakesTest() {
        // TODO: test stakes
    }

}
