/*
 * Wallet/Explorer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountUnstakesResponseUnstakes
 */
public class AccountUnstakesResponseUnstakesTest {
    private final AccountUnstakesResponseUnstakes model = new AccountUnstakesResponseUnstakes();

    /**
     * Model tests for AccountUnstakesResponseUnstakes
     */
    @Test
    public void testAccountUnstakesResponseUnstakes() {
        // TODO: test AccountUnstakesResponseUnstakes
    }

    /**
     * Test the property 'validatorAddress'
     */
    @Test
    public void validatorAddressTest() {
        // TODO: test validatorAddress
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'epochsUntil'
     */
    @Test
    public void epochsUntilTest() {
        // TODO: test epochsUntil
    }

}
