/*
 * Wallet/Explorer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ConstructionBuildErrorAboveMaximumRakeIncrease;
import org.openapitools.client.model.ConstructionBuildErrorCouldNotConstructFees;
import org.openapitools.client.model.ConstructionBuildErrorInvalidStakePermissions;
import org.openapitools.client.model.ConstructionBuildErrorMessageTooLong;
import org.openapitools.client.model.ConstructionBuildErrorMinimumStake;
import org.openapitools.client.model.ConstructionBuildErrorNotEnoughResources;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConstructionBuildError
 */
public class ConstructionBuildErrorTest {
    private final ConstructionBuildError model = new ConstructionBuildError();

    /**
     * Model tests for ConstructionBuildError
     */
    @Test
    public void testConstructionBuildError() {
        // TODO: test ConstructionBuildError
    }

    /**
     * Test the property 'errorType'
     */
    @Test
    public void errorTypeTest() {
        // TODO: test errorType
    }

}
