/*
 * Wallet/Explorer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.InternalServerError;
import org.openapitools.client.model.InvalidJsonError;
import org.openapitools.client.model.InvalidRequestError;
import org.openapitools.client.model.InvalidTransactionError;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConstructionSubmitUnexpectedError
 */
public class ConstructionSubmitUnexpectedErrorTest {
    private final ConstructionSubmitUnexpectedError model = new ConstructionSubmitUnexpectedError();

    /**
     * Model tests for ConstructionSubmitUnexpectedError
     */
    @Test
    public void testConstructionSubmitUnexpectedError() {
        // TODO: test ConstructionSubmitUnexpectedError
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
