/*
 * Wallet/Explorer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Action;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConstructionBuildRequest
 */
public class ConstructionBuildRequestTest {
    private final ConstructionBuildRequest model = new ConstructionBuildRequest();

    /**
     * Model tests for ConstructionBuildRequest
     */
    @Test
    public void testConstructionBuildRequest() {
        // TODO: test ConstructionBuildRequest
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

    /**
     * Test the property 'feePayer'
     */
    @Test
    public void feePayerTest() {
        // TODO: test feePayer
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'disableResourceAllocationAndDestroy'
     */
    @Test
    public void disableResourceAllocationAndDestroyTest() {
        // TODO: test disableResourceAllocationAndDestroy
    }

}
