/*
 * Wallet/Explorer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConstructionBuildErrorInvalidStakePermissions
 */
public class ConstructionBuildErrorInvalidStakePermissionsTest {
    private final ConstructionBuildErrorInvalidStakePermissions model = new ConstructionBuildErrorInvalidStakePermissions();

    /**
     * Model tests for ConstructionBuildErrorInvalidStakePermissions
     */
    @Test
    public void testConstructionBuildErrorInvalidStakePermissions() {
        // TODO: test ConstructionBuildErrorInvalidStakePermissions
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
