/*
 * Wallet/Explorer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InternalServerError
 */
public class InternalServerErrorTest {
    private final InternalServerError model = new InternalServerError();

    /**
     * Model tests for InternalServerError
     */
    @Test
    public void testInternalServerError() {
        // TODO: test InternalServerError
    }

    /**
     * Test the property 'exception'
     */
    @Test
    public void exceptionTest() {
        // TODO: test exception
    }

    /**
     * Test the property 'cause'
     */
    @Test
    public void causeTest() {
        // TODO: test cause
    }

}
