name: build-publish-jars-keygen-workflow
on:
  release:
    types: [ published ]
  push:
    branches:
      - rc\/*
      - release\/*
jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-20.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    name: Build JARs
    steps:
      - name: Set environment variables
        run: |
          echo "GITHUB_REF $GITHUB_REF"
          GH_EVENT_NAME="${{ github.event_name }}"
          if [[ ! -z $GH_EVENT_NAME ]] && [[ "$GH_EVENT_NAME" == "release" ]] ;then
            echo "Workflow triggered by a release event"
            echo "IS_RELEASE=true" >> $GITHUB_ENV
            RELEASE_VERSION="${{ github.event.release.tag_name }}"
            echo "RELEASE_VERSION=$RELEASE_VERSION"
            echo "REF=$RELEASE_VERSION" >> $GITHUB_ENV
          else
            echo "Workflow triggered by push to a branch"
            echo "REF=$GITHUB_REF" >> $GITHUB_ENV
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.REF }}
          fetch-depth: 0
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build radixdlt
        run: |
          if [[ ${{ env.IS_RELEASE }} == "false"  ]];then
            echo "Workflow triggered by push to a branch"
            export CI_VERSION=true
          fi
          version=$(./gradlew radixCiVersion | grep radixdlt-version | cut -d: -f2)
          echo "Version: $version"
          ./gradlew clean build -x test
      - name: Archive radixdlt-core build distributions
        uses: actions/upload-artifact@v2
        with:
          name: build-distribution
          path: |
            radixdlt-core/radixdlt/build/distributions
            retention-days: 1
      - name: Archive radixdlt-core build libraries
        uses: actions/upload-artifact@v2
        with:
          name: build-libraries
          path: |
            radixdlt-core/radixdlt/build/libs
            retention-days: 1
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
  publish-jar:
    needs: build
    environment: publish-artifacts
    name: Publish JAR to Github package repository
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "GITHUB_REF $GITHUB_REF"
          GH_EVENT_NAME="${{ github.event_name }}"
          if [[ ! -z $GH_EVENT_NAME ]] && [[ "$GH_EVENT_NAME" == "release" ]] ;then
            echo "Workflow triggered by a release event"
            echo "IS_RELEASE=true" >> $GITHUB_ENV
            RELEASE_VERSION="${{ github.event.release.tag_name }}"
            echo "RELEASE_VERSION=$RELEASE_VERSION"
            echo "REF=$RELEASE_VERSION" >> $GITHUB_ENV
          else
            echo "Workflow triggered by push to a branch"
            echo "REF=$GITHUB_REF" >> $GITHUB_ENV
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.REF }}
          fetch-depth: 0
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Download distribution artifact
        uses: actions/download-artifact@v2
        with:
          name: build-distribution
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-libraries
      - name: Publish radixdlt-core
        run: |
          if [[ ${{ env.IS_RELEASE }} == "false"  ]];then
            echo "Workflow triggered by a push to a branch"
            export CI_VERSION=true
          fi
          version=$(./gradlew radixCiVersion | grep radixdlt-version | cut -d: -f2)
          echo "Version: $version"
          ./gradlew publish
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
  publish-keygen-docker:
    needs: build
    environment: publish-artifacts
    name: Publish keygen
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "GITHUB_REF $GITHUB_REF"
          GH_EVENT_NAME="${{ github.event_name }}"
          if [[ ! -z $GH_EVENT_NAME ]] && [[ "$GH_EVENT_NAME" == "release" ]] ;then
            echo "Workflow triggered by a release event"
            echo "IS_RELEASE=true" >> $GITHUB_ENV
            RELEASE_VERSION="${{ github.event.release.tag_name }}"
            echo "RELEASE_VERSION=$RELEASE_VERSION"
            echo "REF=$RELEASE_VERSION" >> $GITHUB_ENV
            echo "IMAGE=radixdlt/keygen" >> $GITHUB_ENV
          else
            echo "Workflow triggered by push to a branch"
            echo "REF=$GITHUB_REF" >> $GITHUB_ENV
            echo "IS_RELEASE=false" >> $GITHUB_ENV
            echo "IMAGE=eu.gcr.io/dev-container-repo/keygen" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.REF }}
          fetch-depth: 0
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Download distribution artifact
        uses: actions/download-artifact@v2
        with:
          name: build-distribution
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-libraries
      - name: Prepare Dockerfile context
        run: |
          if [[ ${{ env.IS_RELEASE }} == "false"  ]];then
            export CI_VERSION=true
          fi
          version=$(./gradlew radixCiVersion | grep radixdlt-version | cut -d: -f2)
          echo "Version: $version"
          echo "RADIXDLT_CORE_VERSION_RAW=$version" >> $GITHUB_ENV
          unzip radixdlt-core/radixdlt/build/distributions/radixdlt-${version}.zip
      #todo: dev image even for release commits, only radixdlt on release creation
      - name: Set version
        run: |
          echo "GITHUB_REF $GITHUB_REF"
          if [[ ${{ env.IS_RELEASE }} == "false"  ]];then
            echo "Workflow triggered by a push to a branch"
            export CI_VERSION=true
          fi
          echo "Version: $RADIXDLT_CORE_VERSION_RAW"
          TAG=$(echo $RADIXDLT_CORE_VERSION_RAW | sed 's/~/-/g')
          echo "TAG $TAG"
          echo "RADIXDLT_CORE_VERSION=$TAG" >> $GITHUB_ENV
          echo "PUBLISH=true" >> $GITHUB_ENV
      - name: Login to Dockerhub (release)
        uses: docker/login-action@v1
        if:  "${{ env.IS_RELEASE == 'true' }}"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GCR (rc)
        uses: docker/login-action@v1
        if:  "${{ env.IS_RELEASE == 'false' }}"
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_EU_DEV_JSON_KEY }}
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          file: radixdlt-core/docker/Dockerfile.keygen
          tags: |
            ${{ env.IMAGE }}:${{ env.RADIXDLT_CORE_VERSION }}
          push: ${{ env.PUBLISH }}
          context: ./radixdlt-${{ env.RADIXDLT_CORE_VERSION_RAW }}/
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
