name: build-publish-jars-workflow
on:
  release:
    types: [ published ]
  push:
    branches:
      - main
      - release\/*
jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-22.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5
        with:
          access_token: ${{ github.token }}
  publish-jar:
    environment: publish-artifacts
    name: Publish JAR to Github package repository
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - id: set_environment
        name: Set variables
        uses: ./.github/actions/set-variables
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          ref: ${{ steps.set_environment.outputs.git_ref }}
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@b8204782bbb5f872091ecc5eb9cb7d004e35b1fa
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Publish radixdlt-core
        uses: ./.github/actions/gradle-task
        with:
          is_release: ${{ steps.set_environment.outputs.is_release }}
          gradle_command: publish
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
